#!/usr/bin/env python3
from __future__ import annotations

import argparse
import time
from pathlib import Path
from typing import Any

from _utils import ensure_base_state, find_project_root, git_head, load_config, load_json, load_provider, now_iso, save_json


def next_iteration(root: Path) -> tuple[str, Path]:
    iterations_dir = root / "iterations"
    iterations_dir.mkdir(exist_ok=True)
    max_n = 0
    for entry in iterations_dir.iterdir():
        if not entry.is_dir():
            continue
        prefix = entry.name.split("-", 1)[0]
        if prefix.isdigit():
            max_n = max(max_n, int(prefix))
    dt = time.strftime("%Y%m%d_%H%M%S")
    iter_id = f"{max_n + 1}-{dt}"
    iter_dir = iterations_dir / iter_id
    iter_dir.mkdir(parents=True, exist_ok=False)
    return iter_id, iter_dir


def read_prompt(root: Path, name: str) -> str:
    return (root / ".agent-harness" / "prompts" / name).read_text()


def latest_task_dir(root: Path) -> str | None:
    data = load_json(root / "tasks" / "index.json", {"tasks": []})
    tasks = data.get("tasks", [])
    if not tasks:
        return None
    latest = max(tasks, key=lambda item: item.get("created_at", ""))
    value = latest.get("dir")
    return str(value) if value else None


def write_default_check_report(root: Path, iter_id: str, report_path: Path) -> None:
    task_dir = latest_task_dir(root)
    task_name = None
    status = "not_created"
    phases: list[dict[str, Any]] = []
    if task_dir:
        index_path = root / "tasks" / task_dir / "index.json"
        if index_path.exists():
            index = load_json(index_path)
            task_name = index.get("task")
            phases = index.get("phases", [])
            phase_statuses = [p.get("status") for p in phases]
            if phase_statuses and all(s == "completed" for s in phase_statuses):
                status = "completed"
            elif any(s == "error" for s in phase_statuses):
                status = "error"
            else:
                status = "incomplete"
    save_json(
        report_path,
        {
            "iter_id": iter_id,
            "status": "pass" if status == "completed" else "fail",
            "task": {
                "dir": f"tasks/{task_dir}" if task_dir else None,
                "name": task_name,
                "overall_status": status,
            },
            "phases": phases,
            "issues": [] if status == "completed" else ["Task did not complete."],
            "conclusion": "Generated by run-server fallback check.",
            "carry_over": [],
            "progress": {
                "previous_iter_id": None,
                "signal": "no_prior_run",
                "summary": "",
            },
        },
    )


def run_iteration(provider_name: str | None = None) -> int:
    root = find_project_root()
    ensure_base_state(root)
    config = load_config(root)
    provider = load_provider(provider_name, root)
    execution = config.get("execution", {}) if isinstance(config.get("execution"), dict) else {}
    sandbox_mode = str(execution.get("sandbox_mode", "workspace-write"))
    approval_policy = str(execution.get("approval_policy", "never"))
    prompt_handoff = str(execution.get("prompt_handoff", "stdin"))

    iter_id, iter_dir = next_iteration(root)
    requirement_path = iter_dir / "requirement.md"
    report_path = iter_dir / "check-report.json"

    ideation_prompt = read_prompt(root, "ideation.md")
    provider.run_prompt(
        f"{ideation_prompt}\n\nWrite the requirement to `{requirement_path.relative_to(root)}`.",
        cwd=str(root),
        timeout_sec=int(execution.get("default_timeout_sec", 600)),
        sandbox_mode=sandbox_mode,
        approval_policy=approval_policy,
        prompt_handoff=prompt_handoff,
    )
    if not requirement_path.exists():
        save_json(
            iter_dir / "ideation-error.json",
            {
                "failure_category": "context_insufficient",
                "message": "Ideation did not create requirement.md.",
                "created_at": now_iso(),
            },
        )
        return 1

    pre_build_head = git_head(root)
    build_prompt = read_prompt(root, "build.md")
    provider.run_prompt(
        f"{build_prompt}\n\nIteration id: {iter_id}\nRequirement path: `{requirement_path.relative_to(root)}`",
        cwd=str(root),
        timeout_sec=int(execution.get("build_timeout_sec", 14400)),
        sandbox_mode=sandbox_mode,
        approval_policy=approval_policy,
        prompt_handoff=prompt_handoff,
    )

    check_prompt = read_prompt(root, "check.md")
    provider.run_prompt(
        f"{check_prompt}\n\nIteration id: {iter_id}\nWrite report to `{report_path.relative_to(root)}`.",
        cwd=str(root),
        timeout_sec=int(execution.get("check_timeout_sec", 600)),
        sandbox_mode=sandbox_mode,
        approval_policy=approval_policy,
        prompt_handoff=prompt_handoff,
    )
    if not report_path.exists():
        write_default_check_report(root, iter_id, report_path)

    report = load_json(report_path)
    if report.get("status") == "fail":
        rollback_prompt = read_prompt(root, "rollback.md")
        provider.run_prompt(
            f"{rollback_prompt}\n\nIteration id: {iter_id}\nPre-build SHA: {pre_build_head}\nCheck report: `{report_path.relative_to(root)}`",
            cwd=str(root),
            timeout_sec=int(execution.get("rollback_timeout_sec", 300)),
            sandbox_mode=sandbox_mode,
            approval_policy=approval_policy,
            prompt_handoff=prompt_handoff,
        )
        return 1

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the agent harness iteration loop.")
    parser.add_argument("--once", action="store_true", help="Run one iteration and exit")
    parser.add_argument("--sleep-sec", type=int, default=10, help="Delay between iterations")
    parser.add_argument("--provider", default=None, help="Provider name override")
    args = parser.parse_args()

    while True:
        code = run_iteration(args.provider)
        if args.once or code != 0:
            return code
        time.sleep(args.sleep_sec)


if __name__ == "__main__":
    raise SystemExit(main())
